version: '3.8'

services:
  backend:
    build: ./backend
    container_name: iris-backend
    ports:
      - "8000:8000"
    networks:
      - iris-net

  frontend:
    build: ./frontend
    container_name: iris-frontend
    ports:
      - "8501:8501"
    networks:
      - iris-net
    depends_on:
      - backend

networks:
  iris-net:
    driver: bridge
